In [36]:
from tensorflow.keras.preprocessing.text import one_hot

In [37]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [38]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [39]:
## Define the vocabulary size
voc_size = 10000

In [40]:
## one Hot representation of every word
one_hot_representation = [one_hot(words,voc_size) for words in sent]
one_hot_representation

## The below answers shows that "the word 'the' represented as 2861 the glass is represent as 5720 " means in the index of 5720 is 1(one) out of 10 thousands voc_size 

[[2861, 5720, 1643, 6285],
 [2861, 5720, 1643, 5451],
 [2861, 1895, 1643, 2188],
 [4789, 2484, 4774, 948, 785],
 [4789, 2484, 4774, 948, 2549],
 [5820, 2861, 2976, 1643, 8633],
 [4441, 6510, 8032, 948]]

In [41]:
## word embedding representation 
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

## pad_sentences
every senetence have differet size of words , like some may have six word and some may have five words --> the padding is going to fix the sentence word size     

## means we are adding the zeros in the front or back side

In [42]:
import numpy as np
sen_lenght = 8

In [43]:
embedded_docs = pad_sequences(one_hot_representation,padding='pre',maxlen=sen_lenght)
embedded_docs

array([[   0,    0,    0,    0, 2861, 5720, 1643, 6285],
       [   0,    0,    0,    0, 2861, 5720, 1643, 5451],
       [   0,    0,    0,    0, 2861, 1895, 1643, 2188],
       [   0,    0,    0, 4789, 2484, 4774,  948,  785],
       [   0,    0,    0, 4789, 2484, 4774,  948, 2549],
       [   0,    0,    0, 5820, 2861, 2976, 1643, 8633],
       [   0,    0,    0,    0, 4441, 6510, 8032,  948]])

In [44]:
## if we do post we will zeros at last 
embedded_docs_p = pad_sequences(one_hot_representation,padding='post',maxlen=sen_lenght)
embedded_docs_p

array([[2861, 5720, 1643, 6285,    0,    0,    0,    0],
       [2861, 5720, 1643, 5451,    0,    0,    0,    0],
       [2861, 1895, 1643, 2188,    0,    0,    0,    0],
       [4789, 2484, 4774,  948,  785,    0,    0,    0],
       [4789, 2484, 4774,  948, 2549,    0,    0,    0],
       [5820, 2861, 2976, 1643, 8633,    0,    0,    0],
       [4441, 6510, 8032,  948,    0,    0,    0,    0]])

In [45]:
## feature representation

dim = 10



In [48]:
import warnings
warnings.filterwarnings('ignore')
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sen_lenght))
model.compile('adam','mse')

In [49]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

why this is not showing any output because we did build the model so we have to do the below steps before the model.summary()

In [51]:
# building the model 
## syntax is model.build(batch_size,sent_length)
model.build(input_shape=(None,sen_lenght))

# why None 
'''In deep learning frameworks (like Keras, TensorFlow, PyTorch), the batch size is usually flexible.

None means: “At runtime, I can accept any batch size.”

Example: During training, you may pass batch_size=32, but during inference you might pass batch_size=1.

Keeping it None makes the model general.'''

'In deep learning frameworks (like Keras, TensorFlow, PyTorch), the batch size is usually flexible.\n\nNone means: “At runtime, I can accept any batch size.”\n\nExample: During training, you may pass batch_size=32, but during inference you might pass batch_size=1.\n\nKeeping it None makes the model general.'

In [52]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
## instead of build we can do this also , when we don't know the sen_lenght
'''Builds the model automatically by passing a batch of real data.

Useful if you don’t want to manually specify shapes or if input size may vary.

Sometimes used in exploratory notebooks, but less clean for production.'''

model(np.array(embedded_docs))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)  ## we can see that every word is turn into 10 dimension 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step


array([[[-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.04823826, -0.0491923 , -0.01708589, -0.01624478,
          0.027057  ,  0.02475787,  0.02437856,  0.0387255 ,
          0.0448938 ,  0.02203972],
        [ 0.02945467,  0.00761563,  0.0128533 ,  0.00380547,
         -0.02448976, -0.01320811,  0.01687528,  0.0399196 ,
          0.02906786,  0.0055616 ],
        [-0.04490886, -0.01955278,  0.03511664, -0.0

In [55]:
embedded_docs[0]

array([   0,    0,    0,    0, 2861, 5720, 1643, 6285])

In [58]:
model.predict(np.array(embedded_docs[0]))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [59]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[[-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.02381928, -0.02071827,  0.01820118,  0.02629871,
          0.03024021, -0.04788003,  0.03169017, -0.03292172,
         -0.00117482, -0.04851773],
        [-0.04823826, -0.0491923 , -0.01708589, -0.01624478,
          0.027057  ,  0.02475787,  0.02437856,  0.0387255 ,
          0.0448938 ,  0.02203972],
        [ 0.02945467,  0.00761563,  0.0128533 ,  0.00380547,
         -0.02448976, -0.01320811,  0.01687528,  0.0399196 ,
          0.02906786,  0.0055616 ],
        [-0.04490886, -0.01955278,  0.03511664, -0.0