In [4]:
import numpy as np
from scipy.signal import convolve2d
image = np.array([[1,2,3,0,1],
                  [0,1,2,3,2],
                  [3,1,0,2,1],
                  [2,0,1,3,0],
                  [1,2,0,1,3]])
kernel = np.array([[1,0,-1],
                  [1,0,-1],
                  [1,0,-1]])

In [5]:
image

array([[1, 2, 3, 0, 1],
       [0, 1, 2, 3, 2],
       [3, 1, 0, 2, 1],
       [2, 0, 1, 3, 0],
       [1, 2, 0, 1, 3]])

In [6]:
kernel

array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]])

# program 1 

In [7]:
output = convolve2d(image,kernel,mode = "valid")
print("padding = 0")
print(output)

padding = 0
[[ 1  1 -1]
 [-2  6  0]
 [-5  3  3]]


## program 2 padding = 1

In [9]:
padded = np.pad(image,pad_width = 1,mode = "constant")
output = convolve2d(padded,kernel,mode = "valid")
print(output)

[[ 3  4  0 -2 -3]
 [ 4  1  1 -1 -5]
 [ 2 -2  6  0 -8]
 [ 3 -5  3  3 -6]
 [ 2 -2  2  2 -4]]


## padding = 2

In [11]:
padded = np.pad(image,pad_width = 2,mode = "constant")
output = convolve2d(padded,kernel,mode = "valid")
print(output)

[[ 1  2  2 -2 -2  0 -1]
 [ 1  3  4  0 -2 -3 -3]
 [ 4  4  1  1 -1 -5 -4]
 [ 5  2 -2  6  0 -8 -3]
 [ 6  3 -5  3  3 -6 -4]
 [ 3  2 -2  2  2 -4 -3]
 [ 1  2 -1 -1  3 -1 -3]]


In [12]:
output = convolve2d(image,kernel,mode = "valid")
stride_output = output[::2,::2]
print("Stride_output")
print(stride_output)

Stride_output
[[ 1 -1]
 [-5  3]]


In [13]:
output = convolve2d(image,kernel,mode = "valid")
stride = output[::3,::3]
print("stride_output = 3")
print(stride)

stride_output = 3
[[1]]


In [20]:
pad = np.pad(image,pad_width = 1,mode = "constant")
pad

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 1, 0, 2, 1, 0],
       [0, 2, 0, 1, 3, 0, 0],
       [0, 1, 2, 0, 1, 3, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [21]:
output = convolve2d(pad,kernel,mode = "valid")
stride = output[::2,::2]
print("padding = 1,stride = 2")
print(stride)

padding = 1,stride = 2
[[ 3  0 -3]
 [ 2  6 -8]
 [ 2  2 -4]]


In [22]:
pad = np.pad(image,pad_width=2,mode = "constant")
output = convolve2d(pad,kernel,mode = "valid")
print(output)

[[ 1  2  2 -2 -2  0 -1]
 [ 1  3  4  0 -2 -3 -3]
 [ 4  4  1  1 -1 -5 -4]
 [ 5  2 -2  6  0 -8 -3]
 [ 6  3 -5  3  3 -6 -4]
 [ 3  2 -2  2  2 -4 -3]
 [ 1  2 -1 -1  3 -1 -3]]


In [23]:
output = convolve2d(image,kernel,mode = "same")
print(output)

[[ 3  4  0 -2 -3]
 [ 4  1  1 -1 -5]
 [ 2 -2  6  0 -8]
 [ 3 -5  3  3 -6]
 [ 2 -2  2  2 -4]]


In [24]:
output = convolve2d(image,kernel,mode = "full")
print(output)

[[ 1  2  2 -2 -2  0 -1]
 [ 1  3  4  0 -2 -3 -3]
 [ 4  4  1  1 -1 -5 -4]
 [ 5  2 -2  6  0 -8 -3]
 [ 6  3 -5  3  3 -6 -4]
 [ 3  2 -2  2  2 -4 -3]
 [ 1  2 -1 -1  3 -1 -3]]
